# 🧑‍💻 NumPy Complete Guided Project
**Instructor / Student Colab Notebook** – covers *all* key concepts from `Numpy‑1` to `Numpy‑5`.

*Generated: 08 Aug 2025*


**Table of Contents**

1. [Setup](#setup)  
2. [Array Creation & Dtypes](#creation)  
3. [Array Attributes & Inspection](#attributes)  
4. [Indexing, Slicing, Fancy Indexing](#indexing)  
5. [Reshaping, Transpose & Copies vs Views](#reshape)  
6. [Joining, Splitting, Set & Sorting Ops](#join)  
7. [Arithmetic Ops, Universal Functions](#arithmetic)  
8. [Broadcasting (Rules + Examples)](#broadcast)  
9. [Statistics & Aggregations](#stats)  
10. [Random Numbers & Reproducibility](#random)  
11. [Structured / Recarrays](#structured)  
12. [Linear Algebra Essentials](#linalg)  
13. [File I/O (`npy`, `npz`, `txt`)](#io)  
14. [Datetime64 & Timedelta64](#datetime)  
15. [Masked Arrays & NaNs](#mask)  
16. [Mini‑Project — Fitness Data Analysis](#project)  
17. [Conclusion & Next Steps](#conclusion)  


## <a name='setup'></a>1️⃣ Setup

In [2]:
import numpy as np, math, os, pathlib, types, textwrap, random
print('NumPy version:', np.__version__)

NumPy version: 2.0.2


## <a name='creation'></a>2️⃣ Array Creation & Dtypes

Key functions: `np.array`, `np.arange`, `np.linspace`, `zeros`, `ones`, `full`, `eye`, `identity`, `diag`, `empty`

In [2]:
# EXAMPLE
arr1 = np.array([1, 2, 3], dtype=np.int32)
arr2 = np.linspace(0, 1, 6)
arr3 = np.full((2,3), 7.5)
print(arr1, arr2, arr3, sep="\n")
print("dtypes:", arr1.dtype, arr2.dtype)


[1 2 3]
[0.  0.2 0.4 0.6 0.8 1. ]
[[7.5 7.5 7.5]
 [7.5 7.5 7.5]]
dtypes: int32 float64


In [14]:
# 🖊️ TODO: create a 10×10 chessboard pattern using zeros & ones

import numpy as np

chessboard = np.zeros((10, 10), dtype=int)
chessboard[1::2, ::2] = 1
chessboard[::2, 1::2] = 1

print(chessboard)


[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


## <a name='attributes'></a>3️⃣ Array Attributes & Inspection

`shape`, `ndim`, `size`, `dtype`, `itemsize`, `nbytes`

In [5]:
M = np.arange(12).reshape(3,4)
print('shape', M.shape, 'ndim', M.ndim, 'size', M.size, 'itemsize', M.itemsize, 'total bytes', M.nbytes)


shape (3, 4) ndim 2 size 12 itemsize 8 total bytes 96


In [15]:
# 🖊️ TODO: check memory footprint of a 1000×1000 float64 array

import numpy as np

arr = np.zeros((1000, 1000), dtype=np.float64)

print("Shape:", arr.shape)
print("Item size (bytes):", arr.itemsize)
print("Total size (elements):", arr.size)
print("Total memory (bytes):", arr.nbytes)
print("Total memory (MB):", arr.nbytes / (1024 ** 2))

Shape: (1000, 1000)
Item size (bytes): 8
Total size (elements): 1000000
Total memory (bytes): 8000000
Total memory (MB): 7.62939453125


## <a name='indexing'></a>4️⃣ Indexing, Slicing & Fancy Indexing

In [10]:
a = np.arange(1,26).reshape(5,5)
print(a[:, 0])     # first column
print(a[::2, ::2]) # every 2nd row/col
mask = (a % 3 == 0)
print('multiples of 3:', a[mask])


[ 1  6 11 16 21]
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
multiples of 3: [ 3  6  9 12 15 18 21 24]


In [16]:
# 🖊️ TODO: use fancy indexing to swap first and last rows of `a`

import numpy as np

a = np.arange(1, 26).reshape(5, 5)
print("Original array:\n", a)
a[[0, -1]] = a[[-1, 0]]
print("\nAfter swapping first and last rows:\n", a)

Original array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

After swapping first and last rows:
 [[21 22 23 24 25]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [ 1  2  3  4  5]]


## <a name='reshape'></a>5️⃣ Reshaping, Transpose & Copies vs Views

In [13]:
b = np.arange(8)
B = b.reshape(2,4)
B[0,0] = 99
print('b is modified:', b)
C = b.reshape(2,4).copy()
C[0,0] = -1
print('b unchanged with copy:', b)


b is modified: [99  1  2  3  4  5  6  7]
b unchanged with copy: [99  1  2  3  4  5  6  7]


In [17]:
# 🖊️ TODO: Flatten a 3‑D array into 1‑D using both `ravel` and `flatten`; observe copy vs view.

import numpy as np

a = np.arange(24).reshape(2, 3, 4)
print("Original 3D array:\n", a)

r = a.ravel()
print("\nFlattened using ravel():\n", r)

f = a.flatten()
print("\nFlattened using flatten():\n", f)

a[0, 0, 0] = 999
print("\nAfter modifying a[0,0,0] = 999:")

print("\nRavel result (view):\n", r)
print("Flatten result (copy):\n", f)

Original 3D array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Flattened using ravel():
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Flattened using flatten():
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

After modifying a[0,0,0] = 999:

Ravel result (view):
 [999   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23]
Flatten result (copy):
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


## <a name='join'></a>6️⃣ Joining, Splitting, Set & Sorting Ops

In [6]:
x = np.array([1,3,5]); y = np.array([2,4,6])
xy = np.concatenate([x,y])
print('union', np.union1d(x,y))
print('intersect', np.intersect1d(xy,[1,2,10]))
print('sorted descending', np.sort(xy)[::-1])


union [1 2 3 4 5 6]
intersect [1 2]
sorted descending [6 5 4 3 2 1]


In [8]:
# 🖊️ TODO: split `xy` back into two equal halves using `np.array_split`
halves = np.array_split(xy, 2)
print("First half:", halves[0])
print("Second half:", halves[1])


First half: [1 3 5]
Second half: [2 4 6]


## <a name='arithmetic'></a>7️⃣ Arithmetic Ops & Universal Functions

In [9]:
v = np.arange(5)
print('exp', np.exp(v))
print('sin', np.sin(v))
print('vectorised addition', v + 10)


[0 1 2 3 4]
exp [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
sin [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
vectorised addition [10 11 12 13 14]


In [10]:
# 🖊️ TODO: given degrees [0,30,45,60,90], compute radians and sin values.
import numpy as np

degrees = np.array([0, 30, 45, 60, 90])
radians = np.radians(degrees)
sine_values = np.sin(radians)

print("Degrees:", degrees)
print("Radians:", radians)
print("Sine Values:", sine_values)

Degrees: [ 0 30 45 60 90]
Radians: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Sine Values: [0.         0.5        0.70710678 0.8660254  1.        ]


## <a name='broadcast'></a>8️⃣ Broadcasting Rules

Rules: compare dimensions from right → left; stretch size 1 dims; mismatch error.

In [12]:
row = np.arange(5)
col = np.arange(3).reshape(3,1)
matrix = row + col  # broadcast to 3×5
print(matrix)


[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]]


In [19]:
# 🖊️ TODO: use broadcasting to create a 10×10 multiplication table.

row = np.arange(1, 11)
col = np.arange(1, 11).reshape(10,1)
table = row * col

print("10×10 Multiplication Table:\n", table)


10×10 Multiplication Table:
 [[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


## <a name='stats'></a>9️⃣ Statistics & Aggregations

In [26]:
data = np.random.default_rng(0).integers(1, 100, size=(5,4))
print('data\n', data)
print('row sums', data.sum(axis=1))
print('col means', data.mean(axis=0))


data
 [[85 64 51 27]
 [31  5  8  2]
 [18 81 65 91]
 [50 61 97 73]
 [63 54 56 93]]
row sums [227  46 255 281 266]
col means [49.4 53.  55.4 57.2]


In [27]:
# 🖊️ TODO: compute `np.percentile` (25th, 50th, 75th) of flattened `data`.
flattened = data.flatten()
print(flattened)
p25 = np.percentile(flattened, 25)
p50 = np.percentile(flattened, 50)
p75 = np.percentile(flattened, 75)

print('25th percentile:', p25)
print('50th percentile:', p50)
print('75th percentile:', p75)

[85 64 51 27 31  5  8  2 18 81 65 91 50 61 97 73 63 54 56 93]
25th percentile: 30.0
50th percentile: 58.5
75th percentile: 75.0


## <a name='random'></a>🔟 Random Numbers & Reproducibility

In [3]:
rng = np.random.default_rng(42)
rand_floats = rng.random(5)
rand_ints = rng.integers(low=10, high=50, size=5)
print(rand_floats, rand_ints)
rng2 = np.random.default_rng(42)
assert np.allclose(rand_floats, rng2.random(5))


[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735] [31 49 39 40 38]


In [4]:
# 🖊️ TODO: simulate rolling a fair six‑sided die 100 times; estimate proportion of 6s.
import numpy as np

rng = np.random.default_rng(42)

rolls = rng.integers(1, 7, size=100)

num_sixes = np.sum(rolls == 6)
proportion_sixes = num_sixes / len(rolls)

print("Number of 6s:", num_sixes)
print("Proportion of 6s:", proportion_sixes)


Number of 6s: 14
Proportion of 6s: 0.14


## <a name='structured'></a>1️⃣1️⃣ Structured / Record Arrays

In [5]:
people = np.array([('Alice', 25, 55.0), ('Bob', 30, 85.5)],
                   dtype=[('name','U10'), ('age','i4'), ('weight','f4')])
print(people['name'], people['age'].mean())


['Alice' 'Bob'] 27.5


In [7]:
# 🖊️ TODO: add a new field 'height' to the structured array using `np.lib.recfunctions.append_fields` (hint: pip install?).
import numpy as np
from numpy.lib import recfunctions as rfn

people = np.array([('Alice', 25, 55.0), ('Bob', 30, 85.5)],
                  dtype=[('name','U10'), ('age','i4'), ('weight','f4')])

heights = [160.0, 175.0]

people_with_height = rfn.append_fields(people, 'height', heights, usemask=False)

print(people_with_height)

[('Alice', 25, 55. , 160.) ('Bob', 30, 85.5, 175.)]


## <a name='linalg'></a>1️⃣2️⃣ Linear Algebra Essentials

In [8]:
A = np.random.random((3,3))
b = np.random.random(3)
x = np.linalg.solve(A, b)
print('A·x ≈ b?', np.allclose(A.dot(x), b))


A·x ≈ b? True


In [9]:
# 🖊️ TODO: compute eigenvalues of `A` using `np.linalg.eig`.
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

Eigenvalues: [1.60951515+0.j         0.2585964 +0.47029126j 0.2585964 -0.47029126j]
Eigenvectors:
 [[-0.69359344+0.j         -0.13452604+0.51752948j -0.13452604-0.51752948j]
 [-0.54128463+0.j         -0.17848128-0.47532009j -0.17848128+0.47532009j]
 [-0.47533051+0.j          0.67548592+0.j          0.67548592-0.j        ]]


## <a name='io'></a>1️⃣3️⃣ File I/O (`npy`, `npz`, `txt`)

In [12]:
np.save('array.npy', A)
loaded = np.load('array.npy')
print('loaded equals A?', np.allclose(loaded, A))
np.savez('multi_arrays.npz', A=A, b=b)


loaded equals A? True


In [10]:
# 🖊️ TODO: Use `np.savetxt` to write `data` (from stats section) to CSV then reload with `np.loadtxt`.
import numpy as np

data = np.random.default_rng(0).integers(1, 100, size=(5, 4))

np.savetxt('data.csv', data, delimiter=',', fmt='%d')

loaded_data = np.loadtxt('data.csv', delimiter=',')

print('Loaded equals original?', np.allclose(data, loaded_data))

Loaded equals original? True


## <a name='datetime'></a>1️⃣4️⃣ Datetime64 & Timedelta64

In [14]:
dates = np.arange('2023-01', '2023-04', dtype='datetime64[D]')
delta = dates[1:] - dates[:-1]
print(dates[:5], delta[0])


['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'] 1 days


In [13]:
# 🖊️ TODO: find how many Mondays appear in `dates` array.
import numpy as np

dates = np.arange('2023-01', '2023-04', dtype='datetime64[D]')

weekdays = dates.astype('datetime64[D]').view('int64') % 7

mondays = np.sum(weekdays == 0)

print(f"Number of Mondays: {mondays}")


Number of Mondays: 13


## <a name='mask'></a>1️⃣5️⃣ Masked Arrays & NaNs

In [15]:
arr = np.array([1, 2, np.nan, 4, np.nan])
masked = np.ma.masked_invalid(arr)
print(masked.mean())


2.3333333333333335


In [45]:
# 🖊️ TODO: replace NaNs with column means in a 2‑D array containing NaNs.
import numpy as np

arr = np.array([[1, 2, np.nan],
                [4, np.nan, 6],
                [7, 8, 9]])

col_means = np.nanmean(arr, axis=0)

inds = np.where(np.isnan(arr))

arr[inds] = np.take(col_means, inds[1])

print(arr)


[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


## <a name='project'></a>1️⃣6️⃣ Mini‑Project: Fitness Data Analysis

Load `fitness.txt` (tab‑separated) then follow prompts.

In [17]:
fitness = np.genfromtxt('fitness.txt', delimiter='\t', dtype=None, encoding=None, names=True)
print('columns:', fitness.dtype.names, 'rows:', len(fitness))


columns: ('date', 'step_count', 'mood', 'calories_burned', 'hours_of_sleep', 'bool_of_active', 'weight_kg') rows: 96


In [22]:
# 🖊️ TODO: Monthly step count, sleep vs mood correlation, weekly summary, etc.
import numpy as np

fitness = np.genfromtxt('fitness.txt', delimiter='\t', dtype=None, encoding=None, names=True)
print('columns:', fitness.dtype.names, 'rows:', len(fitness))

from datetime import datetime

def get_month_and_week(date_string):
    dt_obj = datetime.strptime(date_string, '%d-%m-%Y')
    return dt_obj.strftime('%B'), dt_obj.strftime('%Y-%W')

monthly_steps = {}
for date_str, steps in zip(fitness['date'], fitness['step_count']):
    month, _ = get_month_and_week(date_str)
    if month not in monthly_steps:
        monthly_steps[month] = {'total_steps': 0, 'count': 0}
    monthly_steps[month]['total_steps'] += steps
    monthly_steps[month]['count'] += 1

print("\n--- Monthly Step Count ---")
for month, data in monthly_steps.items():
    average_steps = data['total_steps'] / data['count']
    print(f"{month}: Average steps = {average_steps:.2f}")

sleep_mood_groups = {}
for sleep, mood in zip(fitness['hours_of_sleep'], fitness['mood']):
    if sleep not in sleep_mood_groups:
        sleep_mood_groups[sleep] = {'total_mood': 0, 'count': 0}
    sleep_mood_groups[sleep]['total_mood'] += mood
    sleep_mood_groups[sleep]['count'] += 1

print("\n--- Sleep vs. Mood Analysis ---")
for sleep_hours, data in sorted(sleep_mood_groups.items()):
    average_mood = data['total_mood'] / data['count']
    print(f"Average mood for {sleep_hours} hours of sleep: {average_mood:.2f}")

mood_values = fitness['mood'].astype(float)
sleep_values = fitness['hours_of_sleep'].astype(float)
correlation = np.corrcoef(mood_values, sleep_values)[0, 1]
print(f"Pearson correlation coefficient between mood and hours of sleep: {correlation:.4f}")

weekly_summary = {}
for date_str, steps in zip(fitness['date'], fitness['step_count']):
    _, week = get_month_and_week(date_str)
    if week not in weekly_summary:
        weekly_summary[week] = []
    weekly_summary[week].append(steps)

print("\n--- Weekly Summary (Average Step Count) ---")
for week, steps_list in sorted(weekly_summary.items()):
    week_start = datetime.strptime(week + '-1', '%Y-%W-%w').strftime('%b %d')
    week_end = datetime.strptime(week + '-0', '%Y-%W-%w').strftime('%b %d')
    average_steps = sum(steps_list) / len(steps_list)
    print(f"Week starting {week_start} and ending {week_end}: Average steps = {average_steps:.2f}")

columns: ('date', 'step_count', 'mood', 'calories_burned', 'hours_of_sleep', 'bool_of_active', 'weight_kg') rows: 96

--- Monthly Step Count ---
October: Average steps = 3040.42
November: Average steps = 3435.70
December: Average steps = 2889.19
January: Average steps = 1129.22

--- Sleep vs. Mood Analysis ---
Average mood for 2 hours of sleep: 200.00
Average mood for 3 hours of sleep: 144.44
Average mood for 4 hours of sleep: 214.29
Average mood for 5 hours of sleep: 210.81
Average mood for 6 hours of sleep: 231.25
Average mood for 7 hours of sleep: 216.67
Average mood for 8 hours of sleep: 230.00
Average mood for 9 hours of sleep: 300.00
Pearson correlation coefficient between mood and hours of sleep: 0.2104

--- Weekly Summary (Average Step Count) ---
Week starting Oct 02 and ending Oct 08: Average steps = 3843.33
Week starting Oct 09 and ending Oct 15: Average steps = 3401.43
Week starting Oct 16 and ending Oct 22: Average steps = 2952.71
Week starting Oct 23 and ending Oct 29: Ave

## <a name='conclusion'></a>1️⃣7️⃣ Conclusion & Further Practice
Congrats on covering **all core NumPy topics** from your five lecture notebooks!

*Keep experimenting, read the official docs, and try converting your NumPy pipelines into Pandas or JAX for more fun.*